# Generated by Django 2.0.5 on 2018-12-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Harmony', '0002_auto_20181209_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoBoard',
        ),
    ]
